### ISSUE TITLE
split tests from basic to specific

### ISSUE THREAD

**Issue by larsbuntemeyer** [euro-cordex/cc-plugin-cc6#1]
I think we could have:

* a basic MIP test that just tests against a CV table
* inherited from that: more specific MIP dependend tests (e.g. coordinate checks for CORDEX grids, etc...)

This somehow probably depends on 

* https://github.com/ioos/compliance-checker/pull/1091

**Comment by sol1105** [comment]
This has been done with #12, so closing this.
